### ISSUE TITLE
compile issue 

### ISSUE THREAD

**Issue by karter18** [oipwg/miningrigrentals-api-v2#1]
can anyone help with this compile 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'miningrigrentals-api-v2' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData miningrigrentals-api-v2
8 silly fetchNamedPackageData miningrigrentals-api-v2
9 silly mapToRegistry name miningrigrentals-api-v2
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/miningrigrentals-api-v2
13 verbose request uri https://registry.npmjs.org/miningrigrentals-api-v2
14 verbose request no auth needed
15 info attempt registry request try #1 at 12:34:47 AM
16 verbose request id f3bdfadb1a6da1cc
17 verbose etag W/"d252c1d9270fd1d589cb7e7b53e20c41"
18 verbose lastModified Mon, 15 Oct 2018 20:49:53 GMT
19 http request GET https://registry.npmjs.org/miningrigrentals-api-v2
20 http 304 https://registry.npmjs.org/miningrigrentals-api-v2
21 verbose headers { date: 'Fri, 03 May 2019 22:34:48 GMT',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'set-cookie': [ '__cfduid=d2f36393f2366b8dbfab4ea8100395d401556922887; expires=Sat, 02-May-20 22:34:47 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
21 verbose headers   'cf-cache-status': 'MISS',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   'cf-ray': '4d15b450dbfece13-LHR',
21 verbose headers   etag: '"d252c1d9270fd1d589cb7e7b53e20c41"',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   'last-modified': 'Mon, 15 Oct 2018 20:49:53 GMT',
21 verbose headers   vary: 'accept-encoding, accept',
21 verbose headers   'x-amz-meta-rev': '8-b9efa715e4fa7cd6c3914aec3372e085',
21 verbose headers   server: 'cloudflare' }
22 silly get cb [ 304,
22 silly get   { date: 'Fri, 03 May 2019 22:34:48 GMT',
22 silly get     connection: 'keep-alive',
22 silly get     'set-cookie': [ '__cfduid=d2f36393f2366b8dbfab4ea8100395d401556922887; expires=Sat, 02-May-20 22:34:47 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
22 silly get     'cf-cache-status': 'MISS',
22 silly get     'cache-control': 'max-age=300',
22 silly get     'cf-ray': '4d15b450dbfece13-LHR',
22 silly get     etag: '"d252c1d9270fd1d589cb7e7b53e20c41"',
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     'last-modified': 'Mon, 15 Oct 2018 20:49:53 GMT',
22 silly get     vary: 'accept-encoding, accept',
22 silly get     'x-amz-meta-rev': '8-b9efa715e4fa7cd6c3914aec3372e085',
22 silly get     server: 'cloudflare' } ]
23 verbose etag https://registry.npmjs.org/miningrigrentals-api-v2 from cache
24 verbose get saving miningrigrentals-api-v2 to /root/.npm/registry.npmjs.org/miningrigrentals-api-v2/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install miningrigrentals-api-v2 as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /mnt/sdb/miningrigrentals-api-v2
44 error Linux 4.15.0-47-generic
45 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "miningrigrentals-api-v2"
46 error node v4.2.6
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install miningrigrentals-api-v2 as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by orpheus** [comment]
`2 info using npm@3.5.2 3 info using node@v4.2.6`

Try updating your node/npm version. I installed it fine using node@lts

**Comment by karter18** [comment]
how do i update those correctly ?

**Comment by orpheus** [comment]
run these commands in your terminal:

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash`

`command -v nvm` (make sure that prints a `nvm`)

`nvm install --lts`

**Comment by orpheus** [comment]
[This is a node version manager which I recommend](https://github.com/nvm-sh/nvm)

OR 

you can download the latest release from the [OFFICIAL SITE](https://nodejs.org/en/)

**Comment by karter18** [comment]
i just ran those commands and tried to compile again, i have this after the second attempt :
npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "miningrigrentals-api-v2"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install miningrigrentals-api-v2 as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/sdb/miningrigrentals-api-v2/npm-debug.log
root@vps671658:/mnt/sdb/miningrigrentals-api-v2#

**Comment by karter18** [comment]
it looks the same as before i think

**Comment by karter18** [comment]
would you be interested in building/setting this up for me for some coin ?

**Comment by orpheus** [comment]
You’re still using the same node versions. Make sure you update them. If you don’t know how, go through the links I sent above.

**Comment by Canefis** [comment]
Outdated dependencies.
Any updates?
